
# This file is used to configure the Supabase project

project_id = "mwgnpexeymgpzibnkiof"

[api]
# Port to start the API server on
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]

[db]
# Port to start the DB server on
port = 54322

[functions]
[functions.create_user_profile]
verify_jwt = true

[functions.fatsecret-search]
verify_jwt = true

[functions.create-paypal-subscription]
verify_jwt = true

[functions.verify-paypal-payment]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.revise-paypal-subscription]
verify_jwt = true

[functions.suspend-paypal-subscription]
verify_jwt = true

[functions.activate-paypal-subscription]
verify_jwt = true

[functions.cancel-paypal-subscription]
verify_jwt = true

[functions.retry-paypal-payment]
verify_jwt = true

[functions.check-expired-grace-periods]
verify_jwt = false
