
project_id = "mwgnpexeymgpzibnkiof"

[api]
enabled = true
port = 54321
types_path = "types"

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
enabled = true

[functions.create_user_profile]
verify_jwt = true

[studio]
enabled = true
port = 54323
