
project_id = "mwgnpexeymgpzibnkiof"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# Added display name for Google OAuth
display_name = "GatoFit"
