
# This file is used to configure the Supabase project

project_id = "mwgnpexeymgpzibnkiof"

[api]
# Port to start the API server on
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]

[db]
# Port to start the DB server on
port = 54322

[functions]
[functions.create_user_profile]
verify_jwt = true
