
project_id = "mwgnpexeymgpzibnkiof"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

# Configuración de redirectos (importante para autenticación OAuth)
[auth]
site_url = "https://appsecret.gatofit.com"
additional_redirect_urls = ["https://appsecret.gatofit.com/onboarding/app-transition"]
